update task_11
utgak/TestGuru pull request #11
Opened 2021-03-02 18:49 UTC by utgak

2021-03-03 06:33 UTC, VidgarVii requested changes

2021-03-03 06:33 UTC, VidgarVii commented on lib/clients/git_hub_client.rb
> +    super
а зачем тут нужен super?)

2021-03-03 06:33 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +
лишняя строка

2021-03-03 06:33 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    if result.present?
result он всегда будет present если совсем ошибка не выбросится. 
Нужен дополнительный метод типа success? который будет возвращать true/false
А в методе уже проверять создался ли гист в гитхаб

2021-03-03 06:33 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      flash[:notice] =  "success, #{ result[:html_url] }"
Весь контент должен лежать в файлах локализации

2021-03-03 06:33 UTC, VidgarVii commented on app/views/admin/gist/index.html.erb
> +  <th>Question</th>
Весь контент должен лежать в файлах локализации

2021-03-03 06:33 UTC, VidgarVii commented on app/views/admin/_nav.html.erb
>      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
Весь контент должен лежать в файлах локализации

2021-03-03 06:33 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
лучше так. С экономим память:
```ruby
[@question.body, *@question.answers.pluck(:body)].join("\n")
```

2021-03-03 06:33 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      Gist.create!(gist_url: result[:html_url], user: current_user, question: @test_passage.current_question)
result должен иметь метод gist_url который будет возвращать ссылку на гист

2021-03-03 06:33 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  def gist
Gist как полноценная модель заслуживает иметь собственный контроллер. Надо придерживаться REST соглашению и rails way

2021-03-03 06:33 UTC, VidgarVii commented on app/views/admin/gist/_gists.html.erb
> +  <td><%= link_to "#{gists.question.title[0..25]}", admin_question_path(gists.question)  %></td>
здесь лучше использовать хелпер `truncate` - [вот небольшой пост про него](https://makandracards.com/makandra/53287-heads-up-rails-offers-two-similar-means-for-text-truncation)

2021-03-03 13:57 UTC, utgak commented on lib/clients/git_hub_client.rb
> +    super
Rubymine автоматически это дописал

2021-03-03 16:21 UTC, utgak commented on app/controllers/test_passages_controller.rb
> +      Gist.create!(gist_url: result[:html_url], user: current_user, question: @test_passage.current_question)
А в чем разница?

2021-03-04 06:07 UTC, VidgarVii requested changes

2021-03-04 06:07 UTC, VidgarVii commented on app/controllers/gist_controller.rb
> +  def gist
по соглашению rails за создание ресурсов отвечает экшен create

2021-03-04 06:07 UTC, VidgarVii commented on app/controllers/gist_controller.rb
> +    @test_passage = TestPassage.find(params[:id])
по названию параметра id не понятно что он относится к TestPassage. Нужно давать более говорящее название

2021-03-04 06:07 UTC, VidgarVii commented on app/controllers/gist_controller.rb
> +  end
метод #success? относится к сервису GistQuestionService
А сейчас у тебя часть логики создания гиста размазана м/у контроллером и серивисом

2021-03-04 06:07 UTC, VidgarVii commented on lib/clients/git_hub_client.rb
> +    super
убирай

2021-03-04 06:07 UTC, VidgarVii commented on app/views/admin/_nav.html.erb
>      Welcome, <%= current_user.first_name %> Guru |
это должно быть в локале

2021-03-04 06:07 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  private
надо написать сервис так, чтобы он возвращал не непосредственно тот объект, который вернулся с гитхаба, а некий специальный объект, построенный на основании ответа с гитхаба, некий объект специального класса, к примеру `Result` (его можно определить прямо внутри сервиса, как полноценный класс или воспользоваться `Struct`)
такой объект `result` должен нести всю нужную информацию и отзываться на метод `success?` и `url`

2021-03-04 06:07 UTC, VidgarVii commented on app/controllers/gist_controller.rb
> +      flash[:notice] =  "#{ I18n.t("success") }, #{ @result.html_url }"
у сервиса ни где не объявлен метод html_url

2021-03-05 04:29 UTC, VidgarVii commented on app/controllers/gist_controller.rb
> +      flash[:notice] =  "#{ I18n.t("success") }, #{ @result.url }"
I18n поддерживает передачу параметров. Надо использовать
http://rusrails.ru/rails-internationalization-i18n-api#peredacha-peremennyh-v-perevody

Ссылка должна быть кликабельной

2021-03-05 04:34 UTC, VidgarVii commented on app/views/admin/answers/_answer.html.erb
> +  <%= link_to I18n.t('delete'), admin_answer_path(answer), method: :delete,
в представлениях I18n можно не писать. Сразу обращайся к методу t('...')

2021-03-05 04:34 UTC, VidgarVii commented on config/routes.rb
> +  post '/test_passages/:test_passages_id/gist', to: "gist#create"
используй соглашение
resources gist, only: :create 
а параметр test_passages_id можно передать в хелпере
gists_path(test_passages_id: test_passages.id)

2021-03-05 04:34 UTC, VidgarVii commented on config/routes.rb
>    post '/tests/:id/start', to: "tests#start"
этот маршрут должен быть прописан в блоке где объявляется маршруты для теста. Смотри документацию как

2021-03-05 15:03 UTC, VidgarVii requested changes

2021-03-05 15:03 UTC, VidgarVii commented on app/controllers/gist_controller.rb
> +      flash[:alert] = "#{ t("failure") }"
i18n и так возвращает строку. дополнительная инетполяция строк не нужна

2021-03-05 15:03 UTC, VidgarVii commented on app/controllers/gist_controller.rb
> +      flash[:notice] =  "#{ t("success") }, #{ @result.url }"
не исправил прошлое замечание

2021-03-05 15:03 UTC, VidgarVii commented on app/views/tests/index.html.erb
> +    <th><%= I18n.t("action") %></th>
я уже писал, что I18n писать в представлениях не нужно. Обращайся сразу к методу t

2021-03-05 15:26 UTC, utgak commented on app/views/tests/index.html.erb
> +    <th><%= I18n.t("action") %></th>
я это не заметил

2021-03-06 21:35 UTC, merged