Update task_8
utgak/TestGuru pull request #8
Opened 2021-02-22 16:52 UTC by utgak

2021-02-23 16:20 UTC, VidgarVii requested changes

2021-02-23 16:20 UTC, VidgarVii commented on app/controllers/answers_controller.rb
> +    if @answer.save!
если объект будет не валидный то save! выбросит ошибку и до следующей строки дело не дойдет

2021-02-23 16:20 UTC, VidgarVii commented on app/helpers/test_passages_helper.rb
> +    percent = test_passage.correct_questions.to_f / test_passage.test.questions.count * 100.0
вот этот percent пусть экземпляр TestPassage считает

2021-02-23 16:20 UTC, VidgarVii commented on app/helpers/test_passages_helper.rb
> +    if percent >= TestPassage::TEST_PASS_PERCENTAGE
соответственно percent >= TestPassage::TEST_PASS_PERCENTAGE тоже место в классе TestPassage

2021-02-23 16:20 UTC, VidgarVii commented on app/helpers/test_passages_helper.rb
> +      render html: "<p> The test was not passed, <br>
render html это тут лишнее
Строка у тебя тут сложная. Используй ruby код. content_tag ....
Или herodoc. Но лучше освоить первый способ

2021-02-23 16:20 UTC, VidgarVii commented on app/models/test_passage.rb
> +  TEST_PASS_PERCENTAGE = 85
85 это магическое число. Ей место в константе с хорошим говорящем названием

2021-02-23 16:20 UTC, VidgarVii commented on app/models/test_passage.rb
> +  belongs_to :current_question, class_name: 'Question', optional: true
тут всё круто. А вот в миграции нет

2021-02-23 16:20 UTC, VidgarVii commented on db/migrate/20210222012507_drop_table_passed_tests.rb
> +    drop_table :passed_tests, if_exists: true
if_exists это костыль...
окатываемая миграция должна создавать таблицу в том виде в которой она была

2021-02-23 16:20 UTC, VidgarVii commented on db/migrate/20210222011710_create_test_passages.rb
> +      t.integer :correct_questions, default: 0
если есть default наверное есть смысл null убрать?

2021-02-23 16:20 UTC, VidgarVii commented on db/migrate/20210222011710_create_test_passages.rb
> +      t.references :current_question, foreign_key: true
нет такой таблицы current_questions

2021-02-23 16:20 UTC, VidgarVii commented on app/views/test_passages/show.html.erb
> +  </p>
есть смысл утащить этот подсчет в хелпер

2021-02-23 16:20 UTC, VidgarVii commented on app/models/test_passage.rb
> +    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
если юзер не выберет ответ, то этот метод приведёт к багу.
Надо дополнить код

2021-02-24 00:14 UTC, utgak commented on db/migrate/20210222012507_drop_table_passed_tests.rb
> +    drop_table :passed_tests, if_exists: true
Именно это и было в скринкасте

2021-02-24 06:17 UTC, VidgarVii commented on db/migrate/20210222012507_drop_table_passed_tests.rb
> +    drop_table :passed_tests, if_exists: true
https://github.com/rubocop-hq/rails-style-guide#reversible-migration

2021-02-24 18:11 UTC, VidgarVii requested changes

2021-02-24 18:11 UTC, VidgarVii commented on db/migrate/20210222011710_create_test_passages.rb
> +      t.references :question, foreign_key: true
t.references current_question, foreign_key: { to_table: :question }

2021-02-24 18:25 UTC, merged